"""Tripwire over the router functions that dispatch Starlette background tasks.

Locks the inventory of ``background_tasks.add_task`` call sites in
``ts_admin/api/``, and checks that no refusal follows ``create_job`` inside one.
Its job is to make a new 202-dispatching endpoint impossible to land without
someone reading "Refusals on a 202 endpoint" in ``docs/dev/TESTING.md``.

It is a tripwire, not a proof of correctness, and substitutes for nothing: the
covering test for a refusal that must reach the caller is a TestClient test
asserting the status code AND that no ``Job`` row was created. See each test's
docstring for what that test specifically does not cover.
"""

from __future__ import annotations

import ast
from pathlib import Path

_API_DIR = Path(__file__).resolve().parents[2] / "ts_admin" / "api"

# Module-level refusal helpers. One entry today; extend only when a second exists.
_GUARD_CALLS = frozenset({"require_authoritative_metadata"})

# The locked inventory, generated by running _dispatch_functions() and
# cross-checked by hand. A new dispatching endpoint means APPENDING a row (after
# reading the TESTING.md section named above) — never narrow the walker to make
# this green. A row that disappears means either the endpoint was deleted or the
# walker stopped seeing it; establish which before deleting the row.
BACKGROUND_DISPATCH_SITES: frozenset[tuple[str, str]] = frozenset(
    {
        ("archiver", "archiver_dryrun"),
        ("archiver", "archiver_execute"),
        ("archiver", "archiver_restore"),
        ("deleter", "deleter_dryrun"),
        ("deleter", "deleter_execute"),
        ("metadata", "metadata_transfer_dryrun"),
        ("metadata", "metadata_transfer_execute"),
        ("relationships", "build_deep_index"),
        ("sharing", "dryrun"),
        ("sharing", "execute"),
        ("sync", "trigger_sync"),
        ("sync", "trigger_sync_all"),
        ("users", "delete_dryrun"),
        ("users", "delete_execute"),
        ("users", "transfer_dryrun"),
        ("users", "transfer_execute"),
        ("users", "transfer_sharing_execute"),
    }
)

_INVENTORY_DRIFT = (
    "A router function dispatching background_tasks.add_task was added or removed. "
    "Before APPENDING a row: any refusal that must reach the caller has to be checked in "
    "the router BEFORE create_job, and covered by a TestClient test asserting the status "
    "code AND that no Job row was created. Before DELETING a row, confirm the endpoint is "
    "actually gone — a rename of the BackgroundTasks parameter (a no-op to FastAPI, which "
    "binds by type annotation) makes a live dispatch site vanish from this walker, and "
    'deleting the row would bless that blind spot. See "Refusals on a 202 endpoint" in '
    "docs/dev/TESTING.md."
)


def _is_add_task(node: ast.AST) -> bool:
    # Matches the parameter name `background_tasks` syntactically. A router that
    # names its BackgroundTasks parameter anything else would be invisible here;
    # the inventory lock catches the disappearance in the other direction.
    return (
        isinstance(node, ast.Call)
        and isinstance(node.func, ast.Attribute)
        and node.func.attr == "add_task"
        and isinstance(node.func.value, ast.Name)
        and node.func.value.id == "background_tasks"
    )


def _called_name(node: ast.AST, names: frozenset[str] | str) -> bool:
    """True if `node` calls one of `names`, bare (`f()`) or qualified (`m.f()`)."""
    wanted = {names} if isinstance(names, str) else names
    if not isinstance(node, ast.Call):
        return False
    if isinstance(node.func, ast.Name):
        return node.func.id in wanted
    return isinstance(node.func, ast.Attribute) and node.func.attr in wanted


def _dispatch_functions() -> dict[tuple[str, str], ast.FunctionDef | ast.AsyncFunctionDef]:
    found: dict[tuple[str, str], ast.FunctionDef | ast.AsyncFunctionDef] = {}
    # rglob + a recursive walk: a router in a future api/ subpackage, or a
    # dispatch inside a nested function or class body, must not be invisible.
    for path in sorted(_API_DIR.rglob("*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"))
        for func in ast.walk(tree):
            if not isinstance(func, ast.FunctionDef | ast.AsyncFunctionDef):
                continue
            if any(_is_add_task(node) for node in ast.walk(func)):
                found[(path.stem, func.name)] = func
    return found


def test_the_dispatch_site_inventory_is_locked() -> None:
    """Lock the set of routers dispatching background work (tripwire, not a proof)."""
    found = set(_dispatch_functions())
    # Anti-vacuity anchor (S27): an empty walker result would satisfy no equality
    # we care about, so assert the walker found something BEFORE comparing.
    assert found, (
        "walker found NO add_task sites. Either the walker broke (see _is_add_task / "
        "_dispatch_functions) or dispatching moved behind a helper. Establish which — "
        "do not empty the table."
    )
    assert found == set(BACKGROUND_DISPATCH_SITES), _INVENTORY_DRIFT


def test_no_refusal_follows_create_job() -> None:
    """No raise or guard call appears after create_job in a dispatching router.

    NOT a proof that the refusal is in the right place — it is blind to the
    actual S23 shape (a guard that lives ONLY in the background target leaves
    this function with zero raises and passes trivially), and to a refusal raised
    inside a helper called after create_job. Its real subject is the orphaned
    QUEUED Job row: a raise after create_job still returns the correct status,
    because a router's response has not started yet, but the Job row it already
    committed is never dispatched and strands.
    """
    offenders: list[str] = []
    asserted: list[tuple[str, str]] = []
    for (module, name), func in sorted(_dispatch_functions().items()):
        create_job_linenos = [node.lineno for node in ast.walk(func) if _called_name(node, "create_job")]
        if not create_job_linenos:
            continue
        asserted.append((module, name))
        create_job_lineno = min(create_job_linenos)

        for node in ast.walk(func):
            # A bare `raise` is an except handler re-raising: error reporting,
            # not a refusal. `raise Something(...)` IS a refusal, handler or not.
            is_raise = isinstance(node, ast.Raise) and node.exc is not None
            is_guard = _called_name(node, _GUARD_CALLS)
            if not (is_raise or is_guard):
                continue
            if node.lineno <= create_job_lineno:
                continue
            offenders.append(f"{module}:{name}:{node.lineno}")

    # Anti-vacuity anchor (S27): the loop above `continue`s past any function
    # with no create_job call, so the subject set could silently shrink to zero.
    # All 17 sites call create_job today; if a new one genuinely does not, this
    # failing is the correct, informative outcome — read it, then adjust.
    assert len(asserted) == len(BACKGROUND_DISPATCH_SITES), (
        f"asserted over {len(asserted)} of {len(BACKGROUND_DISPATCH_SITES)} dispatch sites. "
        f"Sites with no create_job call: {sorted(set(BACKGROUND_DISPATCH_SITES) - set(asserted))}. "
        "If that list is empty, the inventory table is out of date — read the inventory failure above."
    )
    assert not offenders, (
        "Refusal after create_job — the caller gets the right status code but the "
        f"QUEUED Job row is orphaned and the UI polls it forever: {sorted(set(offenders))}"
    )
