"""Tripwire over the router functions that dispatch Starlette background tasks.

Two assertions, neither of which is a proof of correctness:

1. ``test_the_dispatch_site_inventory_is_locked`` locks the inventory of
   ``background_tasks.add_task`` call sites in ``ts_admin/api/``. It proves only
   that the set has not changed; it CANNOT tell whether any given endpoint needs
   a refusal at all. Its job is to make a new 202-dispatching endpoint impossible
   to land without someone reading "Refusals on a 202 endpoint" in
   ``docs/dev/TESTING.md``.

2. ``test_no_refusal_follows_create_job`` checks ordering within a router
   function. See its docstring for the (substantial) list of things it does NOT
   cover — notably the actual S23 shape, on which it passes trivially.

Neither assertion substitutes for a TestClient test asserting the status code
AND that no ``Job`` row was created.
"""

from __future__ import annotations

import ast
from pathlib import Path

_API_DIR = Path(__file__).resolve().parents[2] / "ts_admin" / "api"

# Module-level refusal helpers. One entry today; extend only when a second exists.
_GUARD_CALLS = frozenset({"require_authoritative_metadata"})

# The locked inventory. Generated by running _dispatch_functions() and
# cross-checked by hand. If the walker disagrees with this table, the walker is
# wrong — fix the walker, do not edit the table.
BACKGROUND_DISPATCH_SITES: frozenset[tuple[str, str]] = frozenset(
    {
        ("archiver", "archiver_dryrun"),
        ("archiver", "archiver_execute"),
        ("archiver", "archiver_restore"),
        ("deleter", "deleter_dryrun"),
        ("deleter", "deleter_execute"),
        ("metadata", "metadata_transfer_dryrun"),
        ("metadata", "metadata_transfer_execute"),
        ("relationships", "build_deep_index"),
        ("sharing", "dryrun"),
        ("sharing", "execute"),
        ("sync", "trigger_sync"),
        ("sync", "trigger_sync_all"),
        ("users", "delete_dryrun"),
        ("users", "delete_execute"),
        ("users", "transfer_dryrun"),
        ("users", "transfer_execute"),
        ("users", "transfer_sharing_execute"),
    }
)

_INVENTORY_DRIFT = (
    "A router function dispatching background_tasks.add_task was added or removed. "
    "Before appending a row: any refusal on this endpoint must be checked in the router "
    "BEFORE create_job, and covered by a TestClient test asserting the status code AND "
    'that no Job row was created. See "Refusals on a 202 endpoint" in docs/dev/TESTING.md.'
)


def _is_add_task(node: ast.AST) -> bool:
    # Matches the parameter name `background_tasks` syntactically. A router that
    # names its BackgroundTasks parameter anything else would be invisible here;
    # the inventory lock catches the disappearance in the other direction.
    return (
        isinstance(node, ast.Call)
        and isinstance(node.func, ast.Attribute)
        and node.func.attr == "add_task"
        and isinstance(node.func.value, ast.Name)
        and node.func.value.id == "background_tasks"
    )


def _dispatch_functions() -> dict[tuple[str, str], ast.FunctionDef | ast.AsyncFunctionDef]:
    found: dict[tuple[str, str], ast.FunctionDef | ast.AsyncFunctionDef] = {}
    for path in sorted(_API_DIR.glob("*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"))
        for func in tree.body:
            if not isinstance(func, ast.FunctionDef | ast.AsyncFunctionDef):
                continue
            if any(_is_add_task(node) for node in ast.walk(func)):
                found[(path.stem, func.name)] = func
    return found


def test_the_dispatch_site_inventory_is_locked() -> None:
    """Lock the set of routers dispatching background work (tripwire, not a proof)."""
    found = set(_dispatch_functions())
    # Anti-vacuity anchor (S27): an empty walker result would satisfy no equality
    # we care about, so assert the walker found something BEFORE comparing.
    assert found, "walker found NO add_task sites — the walker is broken, not the code"
    assert found == set(BACKGROUND_DISPATCH_SITES), _INVENTORY_DRIFT


def test_no_refusal_follows_create_job() -> None:
    """No raise or guard call appears after create_job in a dispatching router.

    NOT a proof that the refusal is in the right place — it is blind to the
    actual S23 shape (a guard that lives ONLY in the background target leaves
    this function with zero raises and passes trivially), and to a refusal raised
    inside a helper called after create_job. Its real subject is the orphaned
    QUEUED Job row: a raise after create_job still returns the correct status,
    because a router's response has not started yet, but the Job row it already
    committed is never dispatched and strands.
    """
    offenders: list[str] = []
    for (module, name), func in sorted(_dispatch_functions().items()):
        create_job_linenos = [
            node.lineno
            for node in ast.walk(func)
            if isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and node.func.id == "create_job"
        ]
        if not create_job_linenos:
            continue
        create_job_lineno = min(create_job_linenos)

        # Nodes inside an except handler are error reporting, not a refusal.
        excluded = {
            id(inner) for node in ast.walk(func) if isinstance(node, ast.ExceptHandler) for inner in ast.walk(node)
        }
        for node in ast.walk(func):
            is_raise = isinstance(node, ast.Raise)
            is_guard = isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and node.func.id in _GUARD_CALLS
            if not (is_raise or is_guard):
                continue
            if id(node) in excluded or node.lineno <= create_job_lineno:
                continue
            offenders.append(f"{module}:{name}:{node.lineno}")

    assert not offenders, (
        "Refusal after create_job — the caller gets the right status code but the "
        f"QUEUED Job row is orphaned and the UI polls it forever: {sorted(set(offenders))}"
    )
